Feature/add redux and axios
Lambda-School-Labs/LabsPT12-Express_Groomer-TeamF-FE pull request #2
Opened 2020-10-13 23:10 UTC by sophiasagan

2020-10-13 23:39 UTC, hmerritt requested changes
Everything looks great with Redux + Axios auth!

One small suggestion: `.env.sample` was deleted when making `.env` but it seems like `.env.sample` is needed for the tests to pass.

It would be great if you could restore `.env.sample` (even though we don't need it ourselves, just for the tests to pass)

2020-10-13 23:48 UTC, hmerritt approved these changes
Looks good! (tests passed which is great 👍 )

2020-10-14 00:29 UTC, josegocampo commented
wow Sophia, you are amazing! good job on this, also good catch Harry!

2020-10-14 00:31 UTC, josegocampo commented on src/state/actions/userActions.js
> +    var user = await authService.getUser();
is there a reason you are using var here :O  just wondering

2020-10-14 00:32 UTC, josegocampo approved these changes
Looks great, thanks a lot for doing this Sophia!

2020-10-14 00:34 UTC, merged